apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cicd-deployment
spec:
  selector:
    matchLabels:
      app: cicd
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd
          image: hamouda1412/cicd_pipeline:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: cicd-ssvc
spec:
  selector:
    app: cicd
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30001  # You can specify a static NodePort if needed
  type: NodePort
